import Head from 'next/head';
import { Box, Button, Center, Container, Heading } from '@chakra-ui/react';

import { useAuth } from '../lib/authentication';

const Card = (props) => {
  return <Box boxShadow="xs" p="6" rounded="md" bg="white" {...props} />;
};

export default function Home() {
  const { user, signin } = useAuth();

  const handleClick = async () => {
    const result = await signin({
      email: 'gigafud@gmail.com',
      password: 'password',
    });
  };

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Center height="100vh">
        <Heading as="h1">Hello {user && user.name}</Heading>
        {}
        <Button onClick={handleClick}>Sign in</Button>
      </Center>
    </Container>
  );
}
